# Generated by Django 5.1.7 on 2025-03-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_time', models.DateTimeField(auto_now_add=True)),
                ('from_place', models.CharField(max_length=255)),
                ('to_place', models.CharField(max_length=255)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Paid to Company', 'Paid to Company')], max_length=50)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
