# Generated by Django 5.1.7 on 2025-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
